#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

#For this example we'll configure the costmap in voxel-grid mode
map_type: costmap
global_frame: map
robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
static_map: true
rolling_window: false

width: 100.0
height: 100.0
resolution: 0.05
inflation_radius: 0.55
cost_scaling_factor: 10.0

#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 2.0
obstacle_range: 3.5
raytrace_range: 4.0

footprint: [[-0.127, -0.127], [-0.18, 0.0], [-0.127, 0.127], [0.0, 0.18], [0.127, 0.127], [0.18, 0.0], [0.127, -0.127], [0.0, -0.18]]
#robot_radius: 0.18

