footprint: [[-0.127, -0.127], [-0.18, 0.0], [-0.127, 0.127], [0.0, 0.18], [0.127, 0.127], [0.18, 0.0], [0.127, -0.127], [0.0, -0.18]]
transform_tolerance: 2.0
map_type: costmap
obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 4.0
 inflation_radius: 0.55
 track_unknown_space: true
 combination_method: 1
inflation_layer:
  enabled:              true
  inflation_radius:     0.55
  cost_scaling_factor: 10.0
  
navfn:
 global_frame: robot_1/map
 update_frequency: 0.5
 publish_frequency: 0.25
 rolling_window: true
 width: 100
 height: 100
 resolution: 0.05
 plugins:
   - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}